package org.test.elasticsearch.inject;

public class Data {

    public String getData() {
        StringBuffer strBuffer = new StringBuffer();
        strBuffer.append("{");
        strBuffer.append("\"Transaction\"							:\"2006-11-08\",");
        strBuffer.append("\"Prix\"									:\"1\",");
        strBuffer.append("\"Date_creation\"						:\"60\",");
        strBuffer.append("\"NetVendeur\"							:\"95000.000000\",");
        strBuffer.append("\"Pays\"									:\"0\",");
        strBuffer.append("\"Nb_chambre\"							:\"88000.000000\",");
        strBuffer.append("\"AnneeConst\"							:\"France\",");
        strBuffer.append("\"Nb_slb\"								:\"1\",");
        strBuffer.append("\"Soussol\"								:\"\",");
        strBuffer.append("\"Nb_garage\"							:\"1\",");
        strBuffer.append("\"Nb_Pieces\"							:\"0\",");
        strBuffer.append("\"Ville\"								:\"0\",");
        strBuffer.append("\"Type_Mandat\"							:\"2\",");
        strBuffer.append("\"NUMSEC\"								:\"AGDE\",");
        strBuffer.append("\"IDTYPE\"								:\"1\",");
        strBuffer.append("\"Date_exp_mandat\"						:\"3500215\",");
        strBuffer.append("\"Surf_sejour\"							:\"2\",");
        strBuffer.append("\"Exposition\"							:\"2012-03-29\",");
        strBuffer.append("\"Surf_hab\"								:\"21\",");
        strBuffer.append("\"Date_mandat\"							:\"\",");
        strBuffer.append("\"Surf_terrain\"							:\"2010-03-29\",");
        strBuffer.append("\"Occupe\"								:\"1\",");
        strBuffer.append("\"Nom_occupant\"							:\"\",");
        strBuffer.append("\"Date_finbail\"							:null,");
        strBuffer.append("\"Telephone_occupant\"					:\"\",");
        strBuffer.append("\"Loyer_occupant\"						:\"0.000000\",");
        strBuffer.append("\"Pourcent_hono\"						:\"0.079545\",");
        strBuffer.append("\"NUMNEGO2\"								:\"\",");
        strBuffer.append("\"Montant_honoraire\"					:\"7000.000000\",");
        strBuffer.append("\"Export_Internet\"						:\"1\",");
        strBuffer.append("\"Etat\"									:\"6\",");
        strBuffer.append("\"Vedette\"								:\"0\",");
        strBuffer.append("\"Accroche_Internet1\"					:\"\",");
        strBuffer.append("\"TaxeFonciere\"							:\"0.000000\",");
        strBuffer.append("\"TaxeHabitation\"						:\"0.000000\",");
        strBuffer.append("\"ChargeMensuelle\"						:\"58.000000\",");
        strBuffer.append("\"EtatGeneral\"							:null,");
        strBuffer.append("\"Texte_presse8\"						:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Adresse\"								:\" aménagé en local associatif\",");
        strBuffer.append("\"Adresse_suite\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Residence\"							:\"APT 1\",");
        strBuffer.append("\"Quartier\"								:\"27 RUE DE L EGALITE\",");
        strBuffer.append("\"Code_postal\"							:\"LA SALAMANDRE\",");
        strBuffer.append("\"RemarqueInterne\"						:\"CENTRE VILLE\",");
        strBuffer.append("\"Syndic\"								:\"34300\",");
        strBuffer.append("\"Notaire\"								:\"Fonctionne aux offres\",");
        strBuffer.append("\"InfoPratique\"							:\"\",");
        strBuffer.append("\"DateCu\"								:\"\",");
        strBuffer.append("\"Nb_Salledeau\"							:\"CLEF AGENCE AGDE RENEE CASSIN\",");
        strBuffer.append("\"RefMandat\"							:null,");
        strBuffer.append("\"NUMAGE\"								:\"0\",");
        strBuffer.append("\"NUMPRO\"								:\"2906\",");
        strBuffer.append("\"NUMPDT\"								:\"35002\",");
        strBuffer.append("\"NUMNEGO\"								:\"35002234\",");
        strBuffer.append("\"NatureChauffage\"						:\"35002362\",");
        strBuffer.append("\"Balcon\"								:\"350029\",");
        strBuffer.append("\"Piscine\"								:\"3\",");
        strBuffer.append("\"Ascenceur\"							:\"\",");
        strBuffer.append("\"Piscinable\"							:\"\",");
        strBuffer.append("\"NumeroEtage\"							:\"0\",");
        strBuffer.append("\"Vue\"									:\"0\",");
        strBuffer.append("\"Mitoyennete\"							:\"3\",");
        strBuffer.append("\"Lotissement\"							:\"\",");
        strBuffer.append("\"Barbecue\"								:\"\",");
        strBuffer.append("\"Pool_house\"							:\"0\",");
        strBuffer.append("\"Vide_sanitaire\"						:\"0\",");
        strBuffer.append("\"Fosse_septique\"						:\"0\",");
        strBuffer.append("\"Tout_egout\"							:\"0\",");
        strBuffer.append("\"Gardien\"								:\"0\",");
        strBuffer.append("\"Terrasse\"								:\"1\",");
        strBuffer.append("\"Menuiserie\"							:\"0\",");
        strBuffer.append("\"Revetement\"							:\"\",");
        strBuffer.append("\"Isolation\"							:\"ALUMINIUM\",");
        strBuffer.append("\"Cloison\"								:\"CARRELAGE\",");
        strBuffer.append("\"AncienneRef\"							:\"\",");
        strBuffer.append("\"Cave\"									:\"\",");
        strBuffer.append("\"Climatisation\"						:\"952861\",");
        strBuffer.append("\"Nb_Etage\"								:\"0\",");
        strBuffer.append("\"Cheminee\"								:\"1\",");
        strBuffer.append("\"Texte_internet1\"						:\"0\",");
        strBuffer.append("\"Texte_vitrine1\"						:\"0\",");
        strBuffer.append("\"Accroche_Internet2\"					:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Texte_presse1\"						:\" aménagé en local associatif\",");
        strBuffer.append("\"Texte_internet2\"						:\" nombreux aménagements possibles.  SANTONI IMMOBILIER- Plus d'informations sur www.santoni.fr\",");
        strBuffer.append("\"Texte_vitrine2\"						:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Accroche_Internet3\"					:\" aménagé en local associatif\",");
        strBuffer.append("\"Texte_presse2\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Texte_internet3\"						:\"\",");
        strBuffer.append("\"Texte_vitrine3\"						:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"AExporter\"							:\" aménagé en local associatif\",");
        strBuffer.append("\"Texte_presse3\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Texte_presse4\"						:\"In the centre of Agde\",");
        strBuffer.append("\"Texte_presse5\"						:\" in a quiet are\",");
        strBuffer.append("\"Texte_presse6\"						:\" 60 m² apartment\",");
        strBuffer.append("\"Nouveau\"								:\" on the ground floor. Many possibilities. Real estate agency SANTONI IMMOBILIER - For more information about this property : www.santoni.co.uk\",");
        strBuffer.append("\"Date_Compromis\"						:\"In the centre of Agde\",");
        strBuffer.append("\"Date_Vente\"							:\" in a quiet are\",");
        strBuffer.append("\"Texte_presse7\"						:\" 60 m² apartment\",");
        strBuffer.append("\"Famille_type\"							:\" on the ground floor. Many possibilities.\",");
        strBuffer.append("\"NUMZON\"								:\"\",");
        strBuffer.append("\"Prix_Estimation\"						:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"CpWeb\"								:\" aménagé en local associatif\",");
        strBuffer.append("\"VilleWeb\"								:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Nb_Parking_int\"						:null,");
        strBuffer.append("\"Nb_Parking_ext\"						:null,");
        strBuffer.append("\"NumCles\"								:\"0\",");
        strBuffer.append("\"Accroche_Vitrine1\"					:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Estimation_Travaux\"					:\" aménagé en local associatif\",");
        strBuffer.append("\"Visite_virtuelle\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Photo1\"								:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Photo2\"								:\" aménagé en local associatif\",");
        strBuffer.append("\"Localisation\"							:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Terr_Facade\"							:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Terr_Profondeur\"						:\" aménagé en local associatif\",");
        strBuffer.append("\"Terr_Clotures\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Terr_Lot\"								:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Terr_Cos\"								:\" aménagé en local associatif\",");
        strBuffer.append("\"Terr_Shon\"							:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Terr_racceau\"							:\"0\",");
        strBuffer.append("\"Terr_Raccgaz\"							:\"2011-07-20\",");
        strBuffer.append("\"Terr_Alignement\"						:\"2011-07-20\",");
        strBuffer.append("\"Forage\"								:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Viager\"								:\" aménagé en local associatif\",");
        strBuffer.append("\"Acces_Handicape\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Int_Balcon\"							:\"2\",");
        strBuffer.append("\"Int_Piscine\"							:\"3500217\",");
        strBuffer.append("\"Int_Terrasse\"							:\"0.000000\",");
        strBuffer.append("\"Prix_Affiche\"							:\"34300\",");
        strBuffer.append("\"Cour\"									:\"AGDE\",");
        strBuffer.append("\"Vue_Mer\"								:\"0\",");
        strBuffer.append("\"Int_Mitoyen\"							:\"0\",");
        strBuffer.append("\"Honoraire_Agence_Loc\"					:\"63\",");
        strBuffer.append("\"Nb_Wc\"								:\"LA SALAMANDRE\",");
        strBuffer.append("\"Note\"									:\"0.000000\",");
        strBuffer.append("\"Terr_Raccelec\"						:\"http://tour.previsite.com/p/ADAPTIMMO/341482984\",");
        strBuffer.append("\"LibZone\"								:\"35002_341482984_2\",");
        strBuffer.append("\"LibSec\"								:\"35002_341482984_3\",");
        strBuffer.append("\"Plain_Pied\"							:\"AGDE\",");
        strBuffer.append("\"ListeSite\"							:\"0\",");
        strBuffer.append("\"Prix_vendu\"							:\"0\",");
        strBuffer.append("\"Date_inactif\"							:\"\",");
        strBuffer.append("\"Ori_vendu\"							:\"\",");
        strBuffer.append("\"Com_vendu\"							:\"0\",");
        strBuffer.append("\"NUMNEGO_vendu\"						:\"0\",");
        strBuffer.append("\"Prox_CV\"								:\"0\",");
        strBuffer.append("\"Prox_Ecole\"							:\"0\",");
        strBuffer.append("\"Prox_Commerce\"						:\"\",");
        strBuffer.append("\"Prox_Bus\"								:\"0\",");
        strBuffer.append("\"Terrain_Plat\"							:\"0\",");
        strBuffer.append("\"Terrain_Arbore\"						:\"0\",");
        strBuffer.append("\"Terrain_A_Amenager\"					:\"0\",");
        strBuffer.append("\"Terrain_Pentu\"						:\"0\",");
        strBuffer.append("\"Terrain_Clos\"							:\"0\",");
        strBuffer.append("\"Style_Rustique\"						:\"95000.000000\",");
        strBuffer.append("\"Style_Contemp\"						:\"0\",");
        strBuffer.append("\"Style_Moderne\"						:\"0\",");
        strBuffer.append("\"Const_Pierres\"						:\"0\",");
        strBuffer.append("\"Const_semi_trad\"						:\"0.000000\",");
        strBuffer.append("\"Const_trad\"							:\"1\",");
        strBuffer.append("\"Const_Prefa\"							:\"3\",");
        strBuffer.append("\"Const_Autre\"							:\"0\",");
        strBuffer.append("\"Garantie_Dec\"							:\"AGDE\",");
        strBuffer.append("\"Garantie_Dom_Ouvr\"					:\"AGDE - CENTRE VILLE\",");
        strBuffer.append("\"Cuisine_Amenagee\"						:\"0\",");
        strBuffer.append("\"Cuisine_Equipee\"						:\"21\",");
        strBuffer.append("\"Cuisine_Americaine\"					:\"39\",");
        strBuffer.append("\"Cuisine_Coin_Cuisine\"					:\"1\",");
        strBuffer.append("\"Cuisine_Vide\"							:\"33\",");
        strBuffer.append("\"Chauff_Bois\"							:\"42\",");
        strBuffer.append("\"Chauff_Gaz\"							:\"28\",");
        strBuffer.append("\"Chauff_Fuel\"							:\"17\",");
        strBuffer.append("\"Chauff_Electrique\"					:\"23\",");
        strBuffer.append("\"Chauff_Solaire\"						:\"40\",");
        strBuffer.append("\"Chauff_Geothermie\"					:\"20\",");
        strBuffer.append("\"Chauff_Clim_rever\"					:\"37\",");
        strBuffer.append("\"Prox_Tramway\"							:\"43\",");
        strBuffer.append("\"Prox_Gare\"							:\"45\",");
        strBuffer.append("\"Prox_Aeroport\"						:\"53\",");
        strBuffer.append("\"Prox_Autoroute\"						:\"5\",");
        strBuffer.append("\"Date_Dernier_Ravalement\"				:\"19\",");
        strBuffer.append("\"Sit_Centre_ville\"						:\"47\",");
        strBuffer.append("\"Sit_Agglo\"							:\"50\",");
        strBuffer.append("\"Sit_Hors_agglo\"						:\"25\",");
        strBuffer.append("\"Sit_Zone_arti\"						:\"35\",");
        strBuffer.append("\"Sit_Zone_indus\"						:\"30\",");
        strBuffer.append("\"Sit_Zone_Pietonne\"					:\"70000.000000\",");
        strBuffer.append("\"Sit_Zone_rurale\"						:null,");
        strBuffer.append("\"Revenu_brut_annuel\"					:\"2\",");
        strBuffer.append("\"R_habitation\"							:\"PAR ROBERT IMMO \",");
        strBuffer.append("\"R_commercial\"							:\"\",");
        strBuffer.append("\"Surf_totale\"							:\"1\",");
        strBuffer.append("\"Surf_sol\"								:\"1\",");
        strBuffer.append("\"Nb_Lots\"								:\"1\",");
        strBuffer.append("\"Raison_sociale\"						:\"1\",");
        strBuffer.append("\"Forme_juridique\"						:\"0\",");
        strBuffer.append("\"Capital_social\"						:\"0\",");
        strBuffer.append("\"Date_creation_fond\"					:\"0\",");
        strBuffer.append("\"Bail_hab\"								:\"0\",");
        strBuffer.append("\"Bail_comm\"							:\"0\",");
        strBuffer.append("\"Bail_precaire\"						:\"0\",");
        strBuffer.append("\"Nb_employe\"							:\"0\",");
        strBuffer.append("\"Surf_bureau\"							:\"1\",");
        strBuffer.append("\"Surf_stockage\"						:\"0\",");
        strBuffer.append("\"Surf_magasin\"							:\"0\",");
        strBuffer.append("\"Surf_logement\"						:\"0\",");
        strBuffer.append("\"Long_vitrine\"							:\"0\",");
        strBuffer.append("\"Haut_plafond\"							:\"0\",");
        strBuffer.append("\"Valeur_stock\"							:\"0\",");
        strBuffer.append("\"Taxe_pro\"								:\"0\",");
        strBuffer.append("\"Texte_presse10\"						:\"0\",");
        strBuffer.append("\"Acces_camion\"							:\"0\",");
        strBuffer.append("\"Prix_vente_metre\"						:\"0\",");
        strBuffer.append("\"Loyer_annuel_metre\"					:\"1\",");
        strBuffer.append("\"Charges_annuel_metre\"					:\"0\",");
        strBuffer.append("\"Nb_Bureaux\"							:\"0\",");
        strBuffer.append("\"Remarque_financier\"					:\"1\",");
        strBuffer.append("\"InterAgence\"							:\"0\",");
        strBuffer.append("\"ListeAgence\"							:\"0\",");
        strBuffer.append("\"Alarme\"								:\"0\",");
        strBuffer.append("\"Portail_Automatique\"					:\"0\",");
        strBuffer.append("\"Arrosage_Automatique\"					:\"1\",");
        strBuffer.append("\"Investisseur\"							:\"0\",");
        strBuffer.append("\"Aspiration_Centralisee\"				:\"1\",");
        strBuffer.append("\"Sans_vis_a_vis\"						:\"0\",");
        strBuffer.append("\"Au_calme\"								:\"0\",");
        strBuffer.append("\"Interphone\"							:null,");
        strBuffer.append("\"Porte_blindee\"						:\"0\",");
        strBuffer.append("\"Meuble\"								:\"0\",");
        strBuffer.append("\"NUMNOT\"								:\"0\",");
        strBuffer.append("\"NUMSYN\"								:\"0\",");
        strBuffer.append("\"SIA\"									:\"0\",");
        strBuffer.append("\"Loc_Saison\"							:\"0\",");
        strBuffer.append("\"Cadastre\"								:\"0\",");
        strBuffer.append("\"Prestige\"								:\"0.000000\",");
        strBuffer.append("\"Prox_Plage\"							:\"0.000000\",");
        strBuffer.append("\"Prox_Port\"							:\"0.000000\",");
        strBuffer.append("\"Prox_Anim\"							:\"0\",");
        strBuffer.append("\"Dist_Centre_Ville\"					:\"0\",");
        strBuffer.append("\"Dist_Ecole\"							:\"0\",");
        strBuffer.append("\"Dist_Commerce\"						:\"\",");
        strBuffer.append("\"Dist_Bus\"								:\"\",");
        strBuffer.append("\"Dist_Autoroute\"						:\"0.000000\",");
        strBuffer.append("\"Dist_Tramway\"							:null,");
        strBuffer.append("\"Dist_Aeroport\"						:\"0\",");
        strBuffer.append("\"Dist_Gare\"							:\"0\",");
        strBuffer.append("\"Dist_Plage\"							:\"0\",");
        strBuffer.append("\"Dist_Port\"							:\"0\",");
        strBuffer.append("\"Dist_Animation\"						:\"0\",");
        strBuffer.append("\"Toiture\"								:\"0\",");
        strBuffer.append("\"Chauff_Elec_Eco\"						:\"0\",");
        strBuffer.append("\"Chauff_Sol\"							:\"0\",");
        strBuffer.append("\"Volet_Elec\"							:\"0\",");
        strBuffer.append("\"Volet_Manuel\"							:\"0\",");
        strBuffer.append("\"Double_Vitrage\"						:\"0.000000\",");
        strBuffer.append("\"Sur_Vitrage\"							:\"0.000000\",");
        strBuffer.append("\"Insert_Cheminee\"						:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Frais_Not_Red\"						:\" aménagé en local associatif\",");
        strBuffer.append("\"Chambre_Hotes\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Texte_presse9\"						:\"0\",");
        strBuffer.append("\"Neuf\"									:\"0.000000\",");
        strBuffer.append("\"Saisie_Nomade\"						:\"0.000000\",");
        strBuffer.append("\"Indice_Photo\"							:\"0.000000\",");
        strBuffer.append("\"Rideau_Metal\"							:\"0\",");
        strBuffer.append("\"VerifAdmin\"							:null,");
        strBuffer.append("\"Duree_Bail\"							:\"0\",");
        strBuffer.append("\"Activite_Auto\"						:null,");
        strBuffer.append("\"Horaire_Ouv\"							:\"0\",");
        strBuffer.append("\"Type_Client\"							:\"0\",");
        strBuffer.append("\"CAN\"									:\"0\",");
        strBuffer.append("\"CAN1\"									:\"0\",");
        strBuffer.append("\"CAN2\"									:\"0\",");
        strBuffer.append("\"CommissionN\"							:\"0\",");
        strBuffer.append("\"CommissionN1\"							:\"1\",");
        strBuffer.append("\"CommissionN2\"							:\"1\",");
        strBuffer.append("\"EBEN\"									:\"0\",");
        strBuffer.append("\"EBEN1\"								:\"0\",");
        strBuffer.append("\"EBEN2\"								:\"0\",");
        strBuffer.append("\"Salaire_ChargeN\"						:\"0\",");
        strBuffer.append("\"Salaire_ChargeN1\"						:\"\",");
        strBuffer.append("\"Salaire_ChargeN2\"						:\"0\",");
        strBuffer.append("\"Vitre_Blindee\"						:null,");
        strBuffer.append("\"DateMajPrix\"							:\"0\",");
        strBuffer.append("\"Copropriete\"							:\"1\",");
        strBuffer.append("\"TypeSurf\"								:\"1\",");
        strBuffer.append("\"Defisc\"								:\"1\",");
        strBuffer.append("\"Accroche_vitrine2\"					:\"\",");
        strBuffer.append("\"Date_Visite\"							:\"\",");
        strBuffer.append("\"Date_courrier\"						:\"\",");
        strBuffer.append("\"Date_email\"							:\"\",");
        strBuffer.append("\"Date_impression\"						:\"\",");
        strBuffer.append("\"Date_Action\"							:\"\",");
        strBuffer.append("\"Date_Catalogue\"						:\"\",");
        strBuffer.append("\"Date_Publicite\"						:\"\",");
        strBuffer.append("\"NUMAPP\"								:\"\",");
        strBuffer.append("\"TauxCommissionApp\"					:\"\",");
        strBuffer.append("\"ResN\"									:\"\",");
        strBuffer.append("\"ResN1\"								:\"\",");
        strBuffer.append("\"ResN2\"								:\"0\",");
        strBuffer.append("\"Accroche_vitrine3\"					:\"0\",");
        strBuffer.append("\"Montagne\"								:\"0\",");
        strBuffer.append("\"Campagne\"								:\"0\",");
        strBuffer.append("\"PetiteVille\"							:\"0\",");
        strBuffer.append("\"GrandeVille\"							:\"1\",");
        strBuffer.append("\"Village\"								:\"0\",");
        strBuffer.append("\"Mer\"									:\"0\",");
        strBuffer.append("\"NUMAGE2\"								:\"0\",");
        strBuffer.append("\"PPC\"									:\"Agde. Centre ville. Appartement de 60m2 en rez de chaussée\",");
        strBuffer.append("\"Edition_presse1\"						:\" aménagé en local associatif\",");
        strBuffer.append("\"Edition_presse2\"						:\" nombreux aménagements possibles. \",");
        strBuffer.append("\"Edition_presse3\"						:\"0\",");
        strBuffer.append("\"Edition_presse4\"						:\"0\",");
        strBuffer.append("\"Edition_presse5\"						:\"10\",");
        strBuffer.append("\"Edition_presse6\"						:\"0\",");
        strBuffer.append("\"Edition_presse7\"						:\"1\",");
        strBuffer.append("\"Edition_presse8\"						:\"0\",");
        strBuffer.append("\"Edition_presse9\"						:\"\",");
        strBuffer.append("\"Edition_presse10\"						:\"\",");
        strBuffer.append("\"PhotoBig1\"							:\"\",");
        strBuffer.append("\"PhotoBig2\"							:\"0.000000\",");
        strBuffer.append("\"PhotoBig3\"							:\"0.000000\",");
        strBuffer.append("\"MotifVente\"							:\"0.000000\",");
        strBuffer.append("\"Surf_Garages\"							:\"0.000000\",");
        strBuffer.append("\"DepPieceNivLot\"						:\"0.000000\",");
        strBuffer.append("\"IDVILLE\"								:\"0.000000\",");
        strBuffer.append("\"Nb_Chambres_RDC\"						:\"0.000000\",");
        strBuffer.append("\"Nb_Photos\"							:\"0.000000\",");
        strBuffer.append("\"DateMAJ\"								:\"0.000000\",");
        strBuffer.append("\"DateMAJPhotos\"						:\"0.000000\",");
        strBuffer.append("\"Special_pro\"							:\"0.000000\",");
        strBuffer.append("\"Videophone\"							:\"0.000000\",");
        strBuffer.append("\"Loi_Robien_Besson\"					:\"0\",");
        strBuffer.append("\"Loi_Borlo\"							:\"2010-04-27\",");
        strBuffer.append("\"Loi_Paul_Girardin\"					:\"1\",");
        strBuffer.append("\"Loi_Demessine\"						:\"1\",");
        strBuffer.append("\"Loi_LMNP_LMP\"							:\"0\",");
        strBuffer.append("\"Loi_Malraux\"							:\"\",");
        strBuffer.append("\"Loi_autres\"							:\"2010-10-27 18:00:00\",");
        strBuffer.append("\"Monu_histo\"							:\"2011-07-01 17:26:58\",");
        strBuffer.append("\"Prix_Initial\"							:\"2011-03-15 12:49:28\",");
        strBuffer.append("\"Indice_Fichier\"						:\"2011-07-01 16:57:21\",");
        strBuffer.append("\"Adsl\"									:null,");
        strBuffer.append("\"Bouquet_Viager\"						:null,");
        strBuffer.append("\"Rente_Viager\"							:\"2010-10-07 18:42:25\",");
        strBuffer.append("\"Tete_Viager\"							:\"0\",");
        strBuffer.append("\"Age_Proprietaire_Viager\"				:\"0\",");
        strBuffer.append("\"Jouissance_Bien_Viager\"				:\"0.000000\",");
        strBuffer.append("\"Tp\"									:\"0.000000\",");
        strBuffer.append("\"Texte_internet4\"						:\"0.000000\",");
        strBuffer.append("\"Texte_internet5\"						:\"\",");
        strBuffer.append("\"Texte_internet6\"						:\"0\",");
        strBuffer.append("\"Accroche_Internet4\"					:\"0\",");
        strBuffer.append("\"Accroche_Internet5\"					:\"0\",");
        strBuffer.append("\"Accroche_Internet6\"					:\"1\",");
        strBuffer.append("\"Texte_vitrine4\"						:\"0\",");
        strBuffer.append("\"Texte_vitrine5\"						:\"0\",");
        strBuffer.append("\"Texte_vitrine6\"						:\"\",");
        strBuffer.append("\"Accroche_Vitrine4\"					:\"0\",");
        strBuffer.append("\"Accroche_Vitrine5\"					:\"\",");
        strBuffer.append("\"Accroche_Vitrine6\"					:\"\",");
        strBuffer.append("\"CodePays\"								:\"\",");
        strBuffer.append("\"Date_Nouveau\"							:\"\",");
        strBuffer.append("\"Texte_internet7\"						:\"\",");
        strBuffer.append("\"Accroche_Internet7\"					:\"\",");
        strBuffer.append("\"Accroche_Vitrine7\"					:\"\",");
        strBuffer.append("\"Texte_vitrine7\"						:\"\",");
        strBuffer.append("\"IDBASSIN\"								:\"\",");
        strBuffer.append("\"Nouveau_SIA_ADAPT\"					:\"\",");
        strBuffer.append("\"IDPANNEAU\"							:\"\",");
        strBuffer.append("\"Loi_Scellier\"							:\"\",");
        strBuffer.append("\"Loi_PLS\"								:\"\",");
        strBuffer.append("\"Indice_Video\"							:null,");
        strBuffer.append("\"IDVILLE_REELLE\"						:\"0\",");
        strBuffer.append("\"Prox_Metro\"							:\"0\",");
        strBuffer.append("\"Dist_Metro\"							:\"111\",");
        strBuffer.append("\"Latitude\"								:\"1\",");
        strBuffer.append("\"Longitude\"					    		:\"4\",");
        strBuffer.append("\"NomProprio\"							:\"2011-09-20 11:44:54\",");
        strBuffer.append("\"adresseMail_Proprio\"					:\"2010-05-17 18:05:49\",");
        strBuffer.append("\"GeolocPrecise\"				    		:\"0\",");
        strBuffer.append("\"LatitudeWeb\"							:\"0\",");
        strBuffer.append("\"LongitudeWeb\"							:\"0\",");
        strBuffer.append("\"AMEPI\"						    		:\"0\",");
        strBuffer.append("\"EtatAMEPI\"					    		:\"0\",");
        strBuffer.append("\"AExporterAMEPI\"						:\"0\",");
        strBuffer.append("\"DateMajAMEPI\"							:\"0\",");
        strBuffer.append("\"CessionLoyerHC\"						:\"0\",");
        strBuffer.append("\"MontantPasDePorte\"					    :\"0\",");
        strBuffer.append("\"MursCommerciaux\"						:\"0\",");
        strBuffer.append("\"SurfCarrez\"							:\"133000.000000\",");
        strBuffer.append("\"Note_DPE\"								:\"19\",");
        strBuffer.append("\"NumSiret\"								:\"0\",");
        strBuffer.append("\"Prox_Lac\"								:\"0.000000\",");
        strBuffer.append("\"Age_Proprietaire2_Viager\"				:\"0.000000\",");
        strBuffer.append("\"Loi_Pass_Foncier\"						:\"1\",");
        strBuffer.append("\"Dist_Lac\"								:\"0\",");
        strBuffer.append("\"LoyerBasseSaison1S\"					:\"0\",");
        strBuffer.append("\"LoyerMoyenneSaison1S\"					:\"1\",");
        strBuffer.append("\"LoyerHauteSaison1S\"					:null,");
        strBuffer.append("\"CapaciteHebergement_Loc\"				:null,");
        strBuffer.append("\"IDPRG_LOT\"						    	:null,");
        strBuffer.append("\"LoyerTresHauteSaison1S\"				:\"\",");
        strBuffer.append("\"LoyerBasseSaison2S\"					:\"\",");
        strBuffer.append("\"LoyerMoyenneSaison2S\"					:\"\",");
        strBuffer.append("\"LoyerHauteSaison2S\"					:null,");
        strBuffer.append("\"LoyerTresHauteSaison2S\"				:null,");
        strBuffer.append("\"LoyerBasseSaison3S\"					:null,");
        strBuffer.append("\"LoyerMoyenneSaison3S\"					:\"\",");
        strBuffer.append("\"LoyerHauteSaison3S\"					:\"\",");
        strBuffer.append("\"LoyerTresHauteSaison3S\"				:\"\",");
        strBuffer.append("\"LoyerBasseSaison4S\"					:\"FR\",");
        strBuffer.append("\"LoyerMoyenneSaison4S\"					:\"2011-04-02 10:58:29\",");
        strBuffer.append("\"LoyerHauteSaison4S\"					:null,");
        strBuffer.append("\"LoyerTresHauteSaison4S\"				:null,");
        strBuffer.append("\"LoyerBasseSaisonWE\"					:null,");
        strBuffer.append("\"LoyerMoyenneSaisonWE\"					:null,");
        strBuffer.append("\"LoyerHauteSaisonWE\"					:\"0\",");
        strBuffer.append("\"LoyerTresHauteSaisonWE\"				:\"1\",");
        strBuffer.append("\"PeriodeBasseSaison\"					:\"0\",");
        strBuffer.append("\"PeriodeMoyenneSaison\"					:\"0\",");
        strBuffer.append("\"PeriodeHauteSaison\"					:\"0\",");
        strBuffer.append("\"PeriodeTresHauteSaison\"				:\"0\",");
        strBuffer.append("\"Chauff_PompeChaleur\"					:\"111\",");
        strBuffer.append("\"BBC\"									:\"0\",");
        strBuffer.append("\"Loi_Scellier_DOM\"						:\"\",");
        strBuffer.append("\"Loi_ZRR\"								:\"0.7559954060859\",");
        strBuffer.append("\"Loi_LMNP_Censi_Bouvard\"				:\"0.0605968036303\",");
        strBuffer.append("\"Loi_Scellier_PLS\"						:\"AIST\",");
        strBuffer.append("\"ActiviteChambreHotes\"					:\"\",");
        strBuffer.append("\"NUMVID_Longue\"					    	:\"0\",");
        strBuffer.append("\"AExporterBoomImmo\"				    	:\"0.7558206375412\",");
        strBuffer.append("\"Consom_DPE\"							:\"0.0609161639768\",");
        strBuffer.append("\"Note_GES\"								:\"\",");
        strBuffer.append("\"Emissions_GES\"					    	:\"0\",");
        strBuffer.append("\"DPE\"									:\"1\",");
        strBuffer.append("\"NUMEXP_DPE\"							:null,");
        strBuffer.append("\"Date_DPE\"								:\"0.000000\",");
        strBuffer.append("\"LoiCarrez\"							    :\"0.000000\",");
        strBuffer.append("\"NUMEXP_Carrez\"						    :\"0\",");
        strBuffer.append("\"DateLoiCarrez\"						    :\"0\",");
        strBuffer.append("\"Amiante\"								:\"D\",");
        strBuffer.append("\"NUMEXP_Amiante\"						:\"\",");
        strBuffer.append("\"DateAmiante\"							:\"0\",");
        strBuffer.append("\"Plomb\"								    :\"0\",");
        strBuffer.append("\"NUMEXP_Plomb\"							:\"0\",");
        strBuffer.append("\"DatePlomb\"							    :\"\",");
        strBuffer.append("\"Termites\"								:\"0.000000\",");
        strBuffer.append("\"NUMEXP_Termites\"						:\"0.000000\",");
        strBuffer.append("\"DateTermites\"							:\"0.000000\",");
        strBuffer.append("\"RisqueTechno\"							:\"0\",");
        strBuffer.append("\"NUMEXP_RisqueTechno\"					:\"0\",");
        strBuffer.append("\"DateRisqueTechno\"						:\"0.000000\",");
        strBuffer.append("\"Gaz\"									:\"0.000000\",");
        strBuffer.append("\"NUMEXP_Gaz\"							:\"0.000000\",");
        strBuffer.append("\"DateGaz\"								:\"0.000000\",");
        strBuffer.append("\"Electricite\"							:\"0.000000\",");
        strBuffer.append("\"NUMEXP_Electricite\"					:\"0.000000\",");
        strBuffer.append("\"DateElectricite\"						:\"0.000000\",");
        strBuffer.append("\"RemarquesExpertises\"					:\"0.000000\",");
        strBuffer.append("\"NonSoumisDPE\"							:\"0.000000\",");
        strBuffer.append("\"NUMEXP_Assainissement\"				:\"0.000000\",");
        strBuffer.append("\"DateAssainissement\"					:\"0.000000\",");
        strBuffer.append("\"Assainissement\"						:\"0.000000\",");
        strBuffer.append("\"Honoraires_Agence_Loc_Proprietaire\"	:\"0.000000\",");
        strBuffer.append("\"DescriptionCharges\"					:\"0.000000\",");
        strBuffer.append("\"IDQUARTIER\"							:\"0.000000\",");
        strBuffer.append("\"Partage\"								:\"0.000000\",");
        strBuffer.append("\"NonSoumisLimitJoursDiffusion\"			:\"0.000000\",");
        strBuffer.append("\"Calitimo\"								:null,");
        strBuffer.append("\"Delegation_Mandat\"					:null,");
        strBuffer.append("\"MotDePasse\"							:null,");
        strBuffer.append("\"HabitationSenior\"						:null,");
        strBuffer.append("\"ListeSiteNego\"						:\"0\",");
        strBuffer.append("\"InterNego\"							:\"0\",");
        strBuffer.append("\"Pourcent_hono_acq\"					:\"0\",");
        strBuffer.append("\"Montant_honoraire_acq\"				:\"0\",");
        strBuffer.append("\"DateActif\"							:\"0\",");
        strBuffer.append("\"AchargeDe\"							:\"0\",");
        strBuffer.append("\"Pourcent_hono_pro\"					:\"0\",");
        strBuffer.append("\"Montant_honoraire_pro\"				:\"\",");
        strBuffer.append("\"Litige\"								:\"1\",");
        strBuffer.append("\"Montant_honoraire_acq_vendu\"			:\"220\",");
        strBuffer.append("\"Montant_honoraire_pro_vendu\"			:\"D\",");
        strBuffer.append("\"DateDispo\"							:\"23\",");
        strBuffer.append("\"DateEcheancePreavis\"					:\"1\",");
        strBuffer.append("\"Type_Travaux\"							:\"0\",");
        strBuffer.append("\"Loi_Duflot\"							:null,");
        strBuffer.append("\"GarantieLoyerImpaye\"					:\"0\",");
        strBuffer.append("\"Chauff_Poele\"							:\"0\",");
        strBuffer.append("\"Chauff_Granules\"						:null,");
        strBuffer.append("\"ExonereDeTaxeFonciere\"				    :\"0\",");
        strBuffer.append("\"NotaireADeterminer\"					:\"0\",");
        strBuffer.append("\"SansSyndic\"							:null,");
        strBuffer.append("\"ChargesMensuellesADeterminer\"			:\"0\",");
        strBuffer.append("\"RenseignementsDerniereAG\"				:\"0\",");
        strBuffer.append("\"CommentairesDerniereAG\"				:null,");
        strBuffer.append("\"DateMajEtat\"							:\"0\",");
        strBuffer.append("\"RetirerDesRappros\"					    :\"0\",");
        strBuffer.append("\"NUMPRO2\"								:null,");
        strBuffer.append("\"NumVoie\"								:\"0\",");
        strBuffer.append("\"IDBAL\"								    :\"0\",");
        strBuffer.append("\"AlerteMiniSiteEnvoye\"					:null,");
        strBuffer.append("\"MiniSiteBien\"							:\"0\",");
        strBuffer.append("\"LibQuartier\"							:\"0\",");
        strBuffer.append("\"DateMAJAdresse\"						:null,");
        strBuffer.append("\"DPE_EtiquetteVierge\"					:\"0\",");
        strBuffer.append("\"NUMACQ_Occupant\"						:\"0\",");
        strBuffer.append("\"Classification\"						:null,");
        strBuffer.append("\"Licence\"								:null,");
        strBuffer.append("\"Nb_PassageParJour\"					:\"0\",");
        strBuffer.append("\"Nb_Couverts\"							:\"0\",");
        strBuffer.append("\"Nb_ClientsParJour\"					:null,");
        strBuffer.append("\"Nb_ChambresFDC\"						:\"0\",");
        strBuffer.append("\"DureeExerciceEnCours\"					:\"0.000000\",");
        strBuffer.append("\"MontantPanierMoyen\"					:\"\",");
        strBuffer.append("\"DateClotureBilan\"						:\"0\",");
        strBuffer.append("\"Aff_InternetCA\"						:\"0\",");
        strBuffer.append("\"Aff_FicheCA\"							:\"0\",");
        strBuffer.append("\"Aff_InternetEBE\"						:\"0\",");
        strBuffer.append("\"Aff_FicheEBE\"							:\"0\",");
        strBuffer.append("\"Aff_InternetResult\"					:\"\",");
        strBuffer.append("\"Aff_FicheResult\"						:\"0\",");
        strBuffer.append("\"FermetureAnnuelle\"					:null,");
        strBuffer.append("\"Nb_CDI\"								:\"0\",");
        strBuffer.append("\"Nb_CDD\"								:\"0\",");
        strBuffer.append("\"Nb_Interim\"							:\"0.000000\",");
        strBuffer.append("\"Nb_Saisonnier\"						:null,");
        strBuffer.append("\"Occupant_PeriodicitePaiements\"		:\"1\",");
        strBuffer.append("\"Occupant_Terme\"						:\"0\",");
        strBuffer.append("\"ActivitesAutorisees\"					:\"0.000000\",");
        strBuffer.append("\"ActivitesInterdites\"					:\"0\",");
        strBuffer.append("\"Indices\"								:\"0.000000\",");
        strBuffer.append("\"RevisionLoyer\"						:\"0.000000\",");
        strBuffer.append("\"Local_BailMixte\"						:null,");
        strBuffer.append("\"Local_BailComm\"						:null,");
        strBuffer.append("\"Local_BailPrecaire\"					:\"0\",");
        strBuffer.append("\"Local_DureeBail\"						:\"0\",");
        strBuffer.append("\"Local_PeriodicitePaiements\"			:\"0\",");
        strBuffer.append("\"Local_Terme\"							:\"0\",");
        strBuffer.append("\"Local_MontantDepotDeGarantie\"			:\"0\",");
        strBuffer.append("\"ChargeLocataire_Article606\"			:\"0\",");
        strBuffer.append("\"ChargeLocataire_TVA\"					:\"0\",");
        strBuffer.append("\"ChargeLocataire_TaxeFonciere\"			:\"0\",");
        strBuffer.append("\"OrduresMenageres_Montant\"				:\"0\",");
        strBuffer.append("\"OrduresMenageres_Description\"			:\"0\",");
        strBuffer.append("\"Prix_EstimationMini\"					:\"\",");
        strBuffer.append("\"Prix_EstimationMaxi\"					:\"2011-07-25 17:37:39\",");
        strBuffer.append("\"ImportRef\"							    :\"0\",");
        strBuffer.append("\"Extraction\"							:\"\",");
        strBuffer.append("\"EvaliaCreate\"							:\"0\",");
        strBuffer.append("\"Surf_DivMini\"							:\"0\",");
        strBuffer.append("\"PosePanneauPasPossible\"				:\"0\",");
        strBuffer.append("\"Prox_RER\"								:\"0\",");
        strBuffer.append("\"Dist_RER\"								:\"\",");
        strBuffer.append("\"Montant_honoraire_acq_ht\"				:\"2013-07-03 16:00:16\",");
        strBuffer.append("\"Montant_honoraire_pro_ht\"				:\"0\",");
        strBuffer.append("\"TauxTVA\"								:\"\",");
        strBuffer.append("\"Montant_honoraire_ht\"					:\"\",");
        strBuffer.append("\"DateRecocheSite\"						:\"\",");
        strBuffer.append("\"IdFFIPAMEPI\"							:\"0\",");
        strBuffer.append("\"Surf_utile\"							:\"0\",");
        strBuffer.append("\"NormeRT2012\"							:\"0\"");
        strBuffer.append("}");

        return strBuffer.toString();
    }

}
